version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - autoconnect_network

  orchestrator:
    build: ./orchestrator
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - DATA_PATH=/data/transactions_autoconnect.csv
      - NUM_WORKERS=3
    volumes:
      - ./data:/data
    restart: on-failure
    networks:
      - autoconnect_network

  worker1:
    build: ./worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: on-failure
    networks:
      - autoconnect_network

  worker2:
    build: ./worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: on-failure
    networks:
      - autoconnect_network

  worker3:
    build: ./worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: on-failure
    networks:
      - autoconnect_network

  aggregator:
    build: ./aggregator
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: on-failure
    networks:
      - autoconnect_network

  api:
    build: ./api
    depends_on:
      - redis
      - aggregator
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    restart: on-failure
    networks:
      - autoconnect_network

networks:
  autoconnect_network:
    driver: bridge

volumes:
  redis_data: